MODEL:
  NAME: "deeplab_resnet101"
  WEIGHTS: "./pretrain/resnet101-5d3b4d8f.pth"
  FREEZE_BN: True
DATASETS:
  SOURCE_TRAIN: "gta5_train"
  TARGET_TRAIN: "cityscapes_train"
  TEST: "cityscapes_val"
INPUT:
  BRIGHTNESS: 0.5
  CONTRAST: 0.5
  SATURATION: 0.5
  HUE: 0.2
  HORIZONTAL_FLIP_PROB_TRAIN: 0.4
SOLVER:
  BASE_LR: 2.5e-4
  MAX_ITER: 62500
  STOP_ITER: 40000
  BATCH_SIZE: 2
  CHECKPOINT_PERIOD: 1000
